### ISSUE TITLE
Attempt a Guiness World Record

### ISSUE THREAD

**Issue by elneilios** [richorama/40#4]
Either,
1. Choose an existing record and beat it! Nominations can be made by friends/family from this list: http://www.guinnessworldrecords.com/explore-records). E.g. http://www.guinnessworldrecords.com/world-records/most-eggs-crushed-with-the-head-in-30-seconds
2. Come up with a new record and register it with Guiness World Records

http://www.guinnessworldrecords.com/set-a-record/individual/standard-application

**Comment by richorama** [comment]
good ideas!
